kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: mjkaye/docker-bind9-multiarch
    tags: latest-amd64

---
kind: pipeline
name: push_manifest

- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: mjkaye/docker-bind9-multiarch:latest
    template: mjkaye/docker-bind9-multiarch:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64
